### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by IzzySoft** [AndreMiras/QrScan#23]
Could you please specify what license your app is published under? Without a license named, it would default to "all rights reserved" – which is not exactly what Open Source means :wink:

Further it would be nice if you could expand the app description a little, e.g. stating what features your app supports. The two screenshots do not tell very much – and even browsing all commits does not reveal a lot in this context.

Thanks a lot!

**Comment by AndreMiras** [comment]
The source code is under MIT license https://github.com/AndreMiras/QrScan/blob/v20190303/LICENSE
Does this answer your question?

Regarding the app description apart from scanning codes it doesn't do much at the moment. But I'll try listing this in the readme then.

**Comment by IzzySoft** [comment]
Thanks! Yes, license question is definitely answered then. Can you give me another ping when the description is updated? I'm asking [because](https://apt.izzysoft.de/fdroid/index/apk/com.github.andremiras.qrscan) :wink:

**Comment by AndreMiras** [comment]
I see, thanks for sharing more context about the request. I'm not sure how they're trying to pull the data such as the license https://apt.izzysoft.de/fdroid/index/apk/com.github.andremiras.qrscan. I can't recall there's something in the Play store console to tell about the license. Maybe it's some metadata in the APK.
Anyway, yes I'll update the `README.md` and Play store to describe furthermore the app and update the ticket

**Comment by IzzySoft** [comment]
Well, that I can answer (the repo is mine): I go by what is visible. Now that you've added the license, it is clearly visible – so I've updated it (would go online with the next sync tomorrow usually, but I've just triggered one now to speed that up). Will update the description as soon as you tell me it's there.

**Comment by AndreMiras** [comment]
But the license has always been there, it's literally the initial commit https://github.com/AndreMiras/QrScan/commit/40e3a5380ebda0cfd6bd06d7bf270227fd6f2e07#diff-9879d6db96fd29134fc802214163b95a
So do you need to do this manually or you have a scraper that does it? If you have a scraper then I don't know how it missed the license :thinking:

**Comment by IzzySoft** [comment]
Funny. Then how did I miss it? Must have had crossed eyes then. Apologies for that!

Yes, initialization is manual (fetching screenshots is semi-automatic). Updates are automatic (if you tag a new release and attach the APK to it, it should pop up in my repo within 24h – and whoever uses my repo with the F-Droid client should get an update notification).

**Comment by IzzySoft** [comment]
Thanks! Description updated on my end (goes life tomorrow). Added a comment on the commit with a little "request for clarification", though. Hope I don't get annoying :wink:
